---
# Prometheus alerting rules
# T166: Alert on high error rate, pod crashes, and other critical issues

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    app: prometheus
data:
  alerts.yml: |
    groups:
    - name: todo_application_alerts
      interval: 30s
      rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: |
          sum(rate(http_requests_total{job="todo-backend",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="todo-backend"}[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # Critical error rate alert
      - alert: CriticalErrorRate
        expr: |
          sum(rate(http_requests_total{job="todo-backend",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="todo-backend"}[5m])) > 0.15
        for: 2m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"

      # High latency alert
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="todo-backend"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High API latency detected"
          description: "P95 latency is {{ $value }}s for the last 5 minutes"

      # Pod crash alert
      - alert: PodCrashLooping
        expr: |
          rate(kube_pod_container_status_restarts_total{namespace="todo-app"}[15m]) > 0
        for: 5m
        labels:
          severity: critical
          component: infrastructure
        annotations:
          summary: "Pod is crash looping"
          description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 15 minutes"

      # Pod not ready alert
      - alert: PodNotReady
        expr: |
          kube_pod_status_phase{namespace="todo-app", phase!="Running"} > 0
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Pod is not ready"
          description: "Pod {{ $labels.pod }} has been in {{ $labels.phase }} state for more than 10 minutes"

      # Database connection alert
      - alert: DatabaseConnectionHigh
        expr: |
          db_connections_active{job="todo-backend"} > 80
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High database connection usage"
          description: "{{ $value }} active database connections"

      # Kafka consumer lag alert
      - alert: KafkaConsumerLag
        expr: |
          kafka_consumer_lag{job="todo-backend"} > 1000
        for: 10m
        labels:
          severity: warning
          component: kafka
        annotations:
          summary: "High Kafka consumer lag"
          description: "Consumer lag is {{ $value }} for topic {{ $labels.topic }}"

      # Kafka publish failure alert
      - alert: KafkaPublishFailure
        expr: |
          rate(kafka_messages_published_total{job="todo-backend",status="error"}[5m])
          /
          rate(kafka_messages_published_total{job="todo-backend"}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          component: kafka
        annotations:
          summary: "High Kafka publish failure rate"
          description: "{{ $value | humanizePercentage }} of Kafka messages are failing to publish"

    - name: infrastructure_alerts
      interval: 60s
      rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: |
          sum(rate(container_cpu_usage_seconds_total{namespace="todo-app"}[5m])) by (pod)
          /
          sum(kube_pod_container_resource_limits{namespace="todo-app",resource="cpu"}) by (pod) > 0.8
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High CPU usage"
          description: "Pod {{ $labels.pod }} is using more than 80% of CPU limit"

      # High memory usage
      - alert: HighMemoryUsage
        expr: |
          sum(container_memory_working_set_bytes{namespace="todo-app"}) by (pod)
          /
          sum(kube_pod_container_resource_limits{namespace="todo-app",resource="memory"}) by (pod) > 0.8
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "High memory usage"
          description: "Pod {{ $labels.pod }} is using more than 80% of memory limit"

      # Disk space low
      - alert: DiskSpaceLow
        expr: |
          (node_filesystem_avail_bytes{mountpoint="/"}
          /
          node_filesystem_size_bytes{mountpoint="/"}) < 0.1
        for: 10m
        labels:
          severity: warning
          component: infrastructure
        annotations:
          summary: "Low disk space"
          description: "Less than 10% disk space available on {{ $labels.instance }}"
